import "@/app/styles/globals.css";

export const metadata = {
  title: "nHost Demo",
  description: "Generated by create next app",
};

export default function HomeLayout({ children }) {
  return <div>{children}</div>;
}
